### ISSUE TITLE
Concurrent conflict? SyntaxError: Unexpected token r

### ISSUE THREAD

**Issue by fritx** [xunxky/node-Tiny-IPC#1]
```plain
SyntaxError: Unexpected token r
    at Object.parse (native)
    at Socket.<anonymous> (/Users/dji/gt-auto/dist/main.js:29256:18)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:531:20)
```

```js
  getClient: function(socketpath){
    var client = function(){
      EventEmitter.call(this);
      var self = this;
      var c = net.connect(socketpath);
      var data ='';
        c.on('data',function(d){
          data = data+d;
          var m = data.split("\n");
          var o = null;
          for(var i = 0 ; i < (m.length-1);i++){
            if(m[i]){
>>            o = JSON.parse(m[i]);
              if(o && o.r && o.r=='global'){
                self.emit('message',o.m);
              }
            }
          }
          data = m[(m.length-1)];
        });
      this.broadcastMessage = function(m){
        c.write(JSON.stringify({r:'global',m:m})+"\n");
      }
    };
    util.inherits(client,EventEmitter);
    return new client();    
  } 
```

**Comment by fritx** [comment]
PS: it was the last version: v0.2.0
now i'm trying v0.2.1...

**Comment by xunxky** [comment]
yes i have zeroed in the issue on line 21.  the problem seems to lie within the masters relay, and of course the clients lack of error handling. 
i will have time for this issue in July.

**Comment by fritx** [comment]
Would be great to see the fix ;)

**Comment by xunxky** [comment]
should be fixed now
